server:
  port: 8078
spring:
  application:
    name: proxy
  cloud:
    gateway:
      routes:
        - id: client
          uri:
            http://localhost:8082/
          predicates:
          - Path=/client/**

eureka:
  client:
     serviceUrl:
      defaultZone: http://localhost:8760/eureka/
